##########
# collectionbuilder-sa
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-sa
##########


collections:
  para:
    sort_by: title
    output: true
  chris:
    sort_by: title
    output: true
  jack:
    sort_by: title
    output: true
  mapobjects:
    output: true
    source: mapobjects.csv
    id_key: objectid
    layout: mapitem

defaults:
  - scope:
      type: para
    values:
      layout: para
  - scope:
      type: chris
    values:
      layout: para
  - scope:
      type: jack
    values:
      layout: para

##########
# URL VARIABLES
#
# url is your gh-pages base, following the pattern: username.github.io
url: 
# baseurl is your github repository's name prefixed with a /
baseurl: 
# location of code, the full url to your github repository
source-code: https://github.com/thecdil/storying_combined

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Storying Extinction
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Responding to the Loss of North Idaho's Mountain Caribou
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Storying Extinction is ..."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: thecdil
keywords: idaho;history;inland northwest

# Organization branding
organization-name: "Center for Digital Inquiry and Learning, University of Idaho Library"
organization-link: https://cdil.lib.uidaho.edu/
organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil-white.png
organization-logo-nav: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil-white.png

##########
# COLLECTION SETTINGS
#
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: storying
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code
# if present, used to add analytics during "production" build only
# google-analytics-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
